version: '3'
services:
  rabbitmq:
    image: rabbitmq:4.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  producer:
    build: ./producer
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq

  statistics:
    build: ./stats_listener
    depends_on:
      - rabbitmq

  dlq:
    build: ./dlq_listener
    depends_on:
      - rabbitmq